default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: mosquitto

camera:
  - platform: mqtt
    topic: inside/thermal1

sensor:
  - platform: mqtt
    name: "Temperature"
    state_topic: "inside/tmp117/0"
    unit_of_measurement: "°C"
  - platform: mqtt
    name: "Evaporator"
    state_topic: "inside/tmp117/1"
    unit_of_measurement: "°C"
